# fly.toml app configuration file generated for borsa-mcp
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'borsa-mcp-ss'
primary_region = 'fra'

[env]
HOST = "0.0.0.0"
PORT = "8000"
LOG_LEVEL = "info"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  
  # Enable connection persistence for MCP sessions
  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[checks.http_health]             # keep MCP /health live
  type     = "http"
  interval = "30s"
  timeout  = "10s"
  path     = "/health"